### ISSUE TITLE
Is it possible to provide a action.yml to make it a github action to support build package in termux?

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-docker#50]
Is it possible to provide a action.yml to make it a github action to support build package in termux?

Such as:

`.github/workflow/main.yml`:

```yaml
jobs:
  build-in-termux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: termux/termux-docker@v0.0.1
        with:
          platforms: x86_64, aarch64 # all
          run: |
            gcc main.c -o main-{{ platform }}
          output: main-*
      - uses: actions/upload-artifact@v3
        with:
          path: |
            main-*
```
